# Generated by Django 2.2.3 on 2019-07-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=70)),
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('telf', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=70)),
            ],
        ),
    ]
