# Generated by Django 2.2.3 on 2019-07-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardiotocografo',
            fields=[
                ('serial', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=70)),
                ('cargo', models.CharField(max_length=12)),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Persona')),
            ],
        ),
    ]
